Code review
ryanmangin/rails-gradebook pull request #1
Opened 2020-09-02 14:35 UTC by ryanmangin

First pass at code review

2020-09-02 16:21 UTC, mikelopez100 commented on app/models/grade.rb
> +    validate :grade_must_be_valid
Awesome use of a custom validator to ensure that our grade model works as it was originally intended.

2020-09-02 16:22 UTC, mikelopez100 commented on app/controllers/grades_controller.rb
> +    @grades = Grade.all
This was a great catch seeing that we should have our instance variables declared in our controllers and pass them along to our views instead of being declared and used in the view, nice one.

2020-09-02 16:25 UTC, mikelopez100 commented on app/controllers/grades_controller.rb
> +  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :create, :update, :destroy]
In using Devise's `before_action :authenticate_user!` we ensure that users that aren't signed in have access to anything they shouldn't, so this was a great way to do that! However, we are using it for every action in the controller so we can omit the `only: [:index, :show, :new, :edit, :create, :update, :destroy]` and it will work the same way.

2020-09-02 16:26 UTC, mikelopez100 commented on app/views/layouts/application.html.erb
> +      <%= link_to 'View Gradebook', grades_path %> -
Nice job catching these style conventions and fixing them using URL helpers.

2020-09-02 16:30 UTC, mikelopez100 commented on spec/requests/grades_spec.rb
> +    describe "GET /index" do
Great work here. There are several other controller actions that must redirect. In total I would recommend making sure that the HTTP routes for index, show, new, create, edit, update, and destroy are all checked. Would you consider verifying all of these before merging?

2020-09-04 23:36 UTC, ryanmangin commented on spec/requests/grades_spec.rb
> +    describe "GET /index" do
added tests for create, update, and destroy

2020-09-04 23:37 UTC, ryanmangin commented on app/controllers/grades_controller.rb
> +  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :create, :update, :destroy]
removed "only" to clean up code

2020-09-04 23:53 UTC, mikelopez100 requested changes
Nice work.

One thing I think we should look into is checking all the potential side-effects of these sad paths. Particularly the creation and deletion. I don't remember off the top of my head how it was done in the Instagram app. I know we are checking for redirection but its possible the app could do the unintended behavior but also redirect us. I'm worried about that case.

Can you remind me what was done in the Instagram app? If there we did something else then we should do the same thing here. But I can't recall.

Also something else we did in the Instagram app was adding in automated testing when pushing or pull requesting using a github workflow found in the .github/workflow directory in our Instagram, copying it over into this repo should add  the CI testing that we want.

2020-09-04 23:53 UTC, mikelopez100 commented on spec/requests/grades_spec.rb
> +    describe "POST /create" do
This one is looking good. I'm trying to think of all the possible side effects of this one. It could be helpful to check the database to see that the count of grades is the same? The instagram assignment has an example of this I believe. Can you take a look and share your thoughts?

2020-09-04 23:53 UTC, mikelopez100 commented on spec/requests/grades_spec.rb
> +    describe "DELETE /grades/id" do
I'm wondering on this one as well. Maybe we should be checking if the count of items in the database is still the same after performing this operation. What are your thoughts?

2020-09-05 00:00 UTC, ryanmangin commented on spec/requests/grades_spec.rb
> +    describe "POST /create" do
so something like this?
expect {
        post grades_url, params: { grade: attributes_for(:grade, :valid) }
}.to change(Grade, :count).by(0)

2020-09-05 00:07 UTC, mikelopez100 commented on spec/requests/grades_spec.rb
> +    describe "POST /create" do
Looks good to me! We also want to ensure that through our PATCH and DELETE don't see any weird behavior also.

2020-09-06 01:03 UTC, mikelopez100 requested changes
Awesome work! I think we have all our sad paths covered now, but I think that we aren't covering every single CRUD possibility in our feature tests. A quick look over should be able to write the last feature testing that we need. We should also set up a branch protection rule in the settings of this repo to make sure that both testing and a code review are required before merging to master.

2020-09-07 02:17 UTC, mikelopez100 approved these changes
Looks good to me, ready to merge!

2020-09-07 20:10 UTC, merged